# Generated by Django 3.2.13 on 2023-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20230402_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
