# Generated by Django 4.1.6 on 2023-02-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket_basketitem_shopimage_shop_category_shop_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sale',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
