# Generated by Django 4.1.6 on 2023-02-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shop_sale_shop_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='sale_price',
        ),
        migrations.CreateModel(
            name='SaleShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(upload_to='sale_products_images')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Sale_Shop',
            },
        ),
    ]
