# Generated by Django 4.1.6 on 2023-02-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_shop_sale_remove_shop_sale_price_saleshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleShop',
        ),
    ]
