# Generated by Django 3.2.16 on 2023-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_saleshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
