# Generated by Django 3.2.16 on 2023-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shop_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='new_price',
        ),
        migrations.AddField(
            model_name='shop',
            name='sale',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
