# Generated by Django 3.2.16 on 2023-03-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_shop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='sale',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
