# Generated by Django 3.2.16 on 2023-03-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_shop_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='image',
            new_name='picture',
        ),
    ]
