# Generated by Django 3.2.16 on 2023-03-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_image_shop_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='picture',
            new_name='image',
        ),
    ]
