# Generated by Django 3.2.16 on 2023-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_picture_shop_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AlterField(
            model_name='shop',
            name='index_image',
            field=models.ImageField(blank=True, upload_to='products_home'),
        ),
    ]
