# Generated by Django 3.2.13 on 2023-03-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/main_images')),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.index')),
            ],
            options={
                'verbose_name_plural': 'IndexImages',
            },
        ),
    ]
