# Generated by Django 3.2.13 on 2023-03-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230330_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image',
        ),
    ]
