# Generated by Django 3.2.13 on 2023-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_index_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image',
            field=models.ImageField(null=True, upload_to='main_images'),
        ),
    ]
