# Generated by Django 3.2.13 on 2023-03-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_index_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image',
        ),
    ]
