# Generated by Django 3.2.13 on 2023-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_indexbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallIndexBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='main_images')),
            ],
            options={
                'verbose_name_plural': 'SmallIndexBanner',
            },
        ),
        migrations.RenameModel(
            old_name='IndexBanner',
            new_name='BigIndexBanner',
        ),
        migrations.AlterModelOptions(
            name='bigindexbanner',
            options={'verbose_name_plural': 'BigIndexBanner'},
        ),
    ]
