# Generated by Django 3.2.13 on 2023-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230331_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigindexbanner',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='smallindexbanner',
            name='description',
            field=models.CharField(max_length=64),
        ),
    ]
