# Generated by Django 3.2.13 on 2023-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230331_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigindexbanner',
            name='dop_desc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bigindexbanner',
            name='dop_desc2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bigindexbanner',
            name='dop_desc3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
