# Generated by Django 3.2.13 on 2023-04-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bannerundervideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerUnderVideo',
            new_name='Achievements',
        ),
    ]
