# Generated by Django 3.2.13 on 2023-04-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_bannerundervideo_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Achievements'},
        ),
    ]
