# Generated by Django 3.2.13 on 2023-04-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_achievements_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
