# Generated by Django 4.2 on 2023-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='latest_index',
            field=models.BooleanField(default=False),
        ),
    ]
